### ISSUE TITLE
Error Using Node v8.2.1

### ISSUE THREAD

**Issue by mcarlotta** [WisePricer/quadro#190]
# Brief issue description

Trying to install Quadro using Node v8.2.1

Issue: 
```js 
Error: internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^
```

# Log

```js
Error: spawn EACCES
    at exports._errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.<anonymous> (/Users/Mike/Desktop/quad_repos/current/wiser_services/map-service/node_modules/dtrace-provider/scripts/install.js:31:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
```

**Comment by igorshapiro** [comment]
@mcarlotta I remember there was an `npm` issue. What version of `npm` are you using?

**Comment by mcarlotta** [comment]
@igorshapiro using npm v5.4.2. I just upgraded node version from `8.2.1 -> 8.7.0` and it seemed to resolve the issue. Will close ticket.
