### ISSUE TITLE
Some of the quadro test are intermittently failing 

### ISSUE THREAD

**Issue by ankurjain86** [WisePricer/quadro#207]
# Brief issue description

Some of the pub sub test case are failing intermittently 

Example:
1) pubsub publish test final retry on final attempt:
     Uncaught Error: Connection closed: 504 (CHANNEL-ERROR) with message "CHANNEL_ERROR - expected 'channel.open'"
      at Object.accept (node_modules/amqplib/lib/connection.js:90:15)
      at Connection.mainAccept [as accept] (node_modules/amqplib/lib/connection.js:63:33)
      at Socket.go (node_modules/amqplib/lib/connection.js:476:48)
      at emitReadable_ (_stream_readable.js:516:10)
      at emitReadable (_stream_readable.js:510:7)
      at addChunk (_stream_readable.js:277:7)
      at readableAddChunk (_stream_readable.js:253:11)
      at Socket.Readable.push (_stream_readable.js:211:10)
      at TCP.onread (net.js:585:20)

  2) AWS SDK profile credentials configures SDK:
     IllegalOperationError: Channel closed
      at Channel.<anonymous> (node_modules/amqplib/lib/channel.js:149:11)
      at Channel.C._rpc (node_modules/amqplib/lib/channel.js:131:8)
      at node_modules/amqplib/lib/channel_model.js:182:10
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.fromNode.Promise.fromCallback (node_modules/bluebird/js/release/promise.js:180:30)
      at Channel.C.cancel (node_modules/amqplib/lib/channel_model.js:181:18)
      at Context.<anonymous> (examples/app/test/pubsub/pubsub_producer_test.js:3:161)
      at <anonymous>

On rebuilding the code all the test case pass. 

https://circleci.com/gh/WisePricer/quadro/444
https://circleci.com/gh/WisePricer/quadro/445

**Comment by igorshapiro** [comment]
It's a concurrency issue. Most likely happens because rabbitmq channel isn't gracefully shut down in the tests.
I'll check it
