### ISSUE TITLE
Logging kills server instance

### ISSUE THREAD

**Issue by ondrej-kvasnovsky** [WisePricer/quadro#210]
# Brief issue description

When the quadro service is running on EC2 in Docker and we call `Q.log.warn` many times, the service is killed.

# Test case example (desirable)

When you call this couple of times, it kills the server: 
```js
Q.log.warn({ statusCode: res.statusCode }, 'Some message...')
```

```js
{"name":"ProxyService","hostname":"ip-xx-xx-xx-xx","pid":7,"level":40,"statusCode":503,"msg":"Some message...","time":"2018-01-18T21:15:21.945Z","v":0}
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:352:12)
    at LogstashStream.sendLog (/app/node_modules/bunyan-logstash-tcp/dist/lib/logstash.js:228:15)
    at LogstashStream.logstashSend [as send] (/app/node_modules/bunyan-logstash-tcp/dist/lib/logstash.js:246:10)
    at LogstashStream.logstashWrite [as write] (/app/node_modules/bunyan-logstash-tcp/dist/lib/logstash.js:116:8)
    at Logger._emit (/app/node_modules/bunyan/lib/bunyan.js:923:22)
    at Logger.warn (/app/node_modules/bunyan/lib/bunyan.js:1045:24)
    at Logger.warn (/app/node_modules/quadro/lib/logger/logger.js:80:31)
    at onResponse (/app/services/server/middlewares/response_metrics.js:12:15)
    at /app/node_modules/http-mitm-proxy/lib/proxy.js:983:12
    at /app/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/app/node_modules/async/dist/async.js:1003:9)
    at eachOf (/app/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/app/node_modules/async/dist/async.js:3145:5)
    at Proxy._onResponse (/app/node_modules/http-mitm-proxy/lib/proxy.js:982:9)
    at ClientRequest.proxyToServerRequestComplete (/app/node_modules/http-mitm-proxy/lib/proxy.js:746:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:585:20)
```

# Expected outcome

Logging should never kill a server.

# Actual outcome

Logging kills the server instance.

**Comment by tomeresk** [comment]
By the error it seems the problem is with the logging using Logstash and not the local file logging. Might be possible that the server receiving the logs is not able to handle the load rather than a Quadro issue.

**Comment by igorshapiro** [comment]
@tomeresk Yep, though the process shouldn't fail. So it's 2 distinct issues

**Comment by dkvasnicka** [comment]
Fortunately, no Wiser apps seem to be using this feature any more. Having a logging facility directly depend on networking is a _really_ bad idea ;)
